### ISSUE TITLE
Off Hand Durability

### ISSUE THREAD

**Issue by Bobster202** [AlabasterLeking/Crabbers-Delight#19]
Not completely sure why but using this mod at its latest version (1.1.5) causes off hand items to lose durability whilst mining.

-- Tested on a new Curse Forge profile with only "Geckolib", "Farmer's Delight", and "Crabber's Delight" installed, 

Love the mod!

**Comment by mahjerion** [comment]
Can confirm, had this issue crop up on Craft to Exile 2, localized it to this mod. When going back to 1.1.4a the offhand durability is fine.

**Comment by AlabasterLeking** [comment]
Is this to mean, if you have two items held with durability that it will use durability on the other item? And this is not when using the crab claw?

**Comment by Bobster202** [comment]
That's correct. If I mine blocks or place blocks with my main hand, the durability of my shield in the off hand will go down.

**Comment by NoMoreStars** [comment]
Been having this problem as well in my own mod pack. Kept wondering where my shields ended up going to.

**Comment by AlabasterLeking** [comment]
This is now fixed in 1.1.5a. Thanks to everyone for reporting!
