### ISSUE TITLE
Crab cakes

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [AlabasterLeking/Crabbers-Delight#2]
What is the recipe? Jei doesn't show it. 
Crabber's Delight 1.0.1.

**Comment by AlabasterLeking** [comment]
It appears I forgot to add a recipe for this - thats embarrasing

I will release an update tonight hopefully to add the recipe and fix this, thanks for catching it!

**Comment by AlabasterLeking** [comment]
This is now fixed in 1.0.3, you can get it from the Curseforge or Modrinth pages
