### ISSUE TITLE
Crash at launch on 1.19.2 with version 1.1.4

### ISSUE THREAD

**Issue by Lictor000** [AlabasterLeking/Crabbers-Delight#22]
I was creating my modpack (MC 1.19..2) and it crashed on launch. I found the probable cause to be Crabbers Delight by removing few mods at a time.
It seems that this only happens with version 1.1.4 of the mod, everything works fine with 1.1.2.
Crash report here https://pastebin.com/0zN7M13p

**Comment by AlabasterLeking** [comment]
Im curious as to if this is caused by Crabber's Delight, the logs dont show anything particular to it. Could you point me to a particular line that led you to that conclusion?

**Comment by Lictor000** [comment]
Hi, sadly I'm not very good at interpreting these reports and couldn't notice anything that strikes the eye (it's almost gibberish to me).
In the end, I reached my conclusion only by deactivating few mods at a time and doing multiple tests.
Deactivating Crabber's delight 1.1.4 (and only that mod from the list) the game starts up without issues.
Downgrading to 1.1.2 the game runs fine, so it seemed reasonable to me that the issue was there, but again I'm no expert in this.

**Comment by AlabasterLeking** [comment]
Looks like you are missing GeckoLib which is a requirement for 1.1.4

**Comment by Lictor000** [comment]
Don't know how I missed that, feel dumb now. Usually the game straights up tells you "hey, you're missing this", but this time it just crashed.
Thanks a lot.

**Comment by AlabasterLeking** [comment]
Glad I could help! I will have to check and see why it didnt warn about it not being present
