### ISSUE TITLE
Update Chinese translation

### ISSUE THREAD

**Issue by ghost** [AlabasterLeking/Crabbers-Delight#23]
I have made new Chinese translation files for this mod:
https://github.com/0000729735256/Crabbers_Delight_Chinese_Translation

**Comment by Junnaturefox** [comment]
The following is for zh_cn.json only
以下内容仅针对 zh_cn.json

1. Your localisation file is not aligned to the existing en_us.json lines.
1 . 你的本地化文件并未对齐现有的 en_us.json 行数

2. Please explain why "Clawster" is translated as "螯龙"?
2 . 请解释为什么将 “Clawster” 翻译为 “螯龙”？

3. The existing Bucket of Chum contains other non-fish mobs, so "Chum" should not be crudely translated as "鱼饵".
3 . 现有的 Bucket of Chum 中包含其他非鱼类生物，故 “Chum” 不应粗暴的翻译为 “鱼饵”

4. "木棍" in "Make your first crab trap with ropes, steps and sticks" is mistranslated as "棍子".
4 . “用绳子、台阶和棍子制作你的第一个螃蟹陷阱” 中的 “棍子” 翻译错误，应为 “木棍”

5. "Sea-Stars" in "Reach For The Sea-Stars!" is mistranslated as "星星".
5 . 原文为 "Reach For The Sea-Stars!"，Sea-Stars 怎么就变为星星了？

**Comment by ghost** [comment]
> The following is for zh_cn.json only 以下内容仅针对 zh_cn.json
> 
> 1. Your localisation file is not aligned to the existing en_us.json lines.
>    1 . 你的本地化文件并未对齐现有的 en_us.json 行数
> 2. Please explain why "Clawster" is translated as "螯龙"?
>    2 . 请解释为什么将 “Clawster” 翻译为 “螯龙”？
> 3. The existing Bucket of Chum contains other non-fish mobs, so "Chum" should not be crudely translated as "鱼饵".
>    3 . 现有的 Bucket of Chum 中包含其他非鱼类生物，故 “Chum” 不应粗暴的翻译为 “鱼饵”
> 4. "木棍" in "Make your first crab trap with ropes, steps and sticks" is mistranslated as "棍子".
>    4 . “用绳子、台阶和棍子制作你的第一个螃蟹陷阱” 中的 “棍子” 翻译错误，应为 “木棍”
> 5. "Sea-Stars" in "Reach For The Sea-Stars!" is mistranslated as "星星".
>    5 . 原文为 "Reach For The Sea-Stars!"，Sea-Stars 怎么就变为星星了？


I apologize for the earlier issues. I've made some modifications to my language files in an attempt to resolve these problems. Please accept my apologies for the errors!!
